apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloservice
  name: helloservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloservice
    spec:
      containers:
      - image: frankye2099/helloservice:0.0.3
        name: helloservice
        envFrom:
          - configMapRef:
              name: hello-config
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloservice
  name: helloservice
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloservice
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloservice
  name: helloservice-http
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloservice
  type: LoadBalancer
status:
  loadBalancer: {}  
