apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloservice
  name: helloservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloservice
    spec:
      containers:
      - image: frankye2099/helloservice
        name: helloservice
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloservice
  name: helloservice
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloservice
  type: ClusterIP
status:
  loadBalancer: {}
